services:
  netflix-cloud:
    build:
      context: .
      args:
        VITE_TMDB_API_KEY: ${VITE_TMDB_API_KEY}
    container_name: netflix-cloud
    ports:
      - "8081:80"
    restart: unless-stopped
